In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Initiation of data



In [185]:
def calc_K(pk,rhat,vxmin,dvx,nx,vymin,dvy,ny,vzmin,dvz,nz) :
    '''Calculate the values of K simultaneously for all bins'''
    K = np.zeros((nx,ny,nz))
    vmin = np.array([vxmin,vymin,vzmin])
    dv = np.array([dvx,dvy,dvz])
    
    vxmax, vymax, vzmax = vxmin+nx*dvx,vymin+ny*dvy,vzmin+nz*dvz
    # Find intersections along one dimension (say x)
    
    vx_bins = np.arange(vxmin, vxmax+dvx, dvx)
    vy_bins = np.arange(vymin, vymax+dvy, dvy)
    vz_bins = np.arange(vzmin, vzmax+dvz, dvz)
    
    #v_space = np.array([vx_bins,vy_bins,vz_bins])
    
    pkx, pky, pkz = pk
    
    if np.linalg.norm(rhat)!=1:
        raise ValueError('rhat must be a unit vector')

    rhatx, rhaty, rhatz = rhat
    
    vrx = (vx_bins-pkx)/rhatx
    vry = (vy_bins-pky)/rhaty
    vrz = (vz_bins-pkz)/rhatz
    
    vrmax = min(max(vrx),max(vry),max(vrz))
    vrmin = max(min(vrx),min(vry),min(vrz))
    
    vrx = vrx[(vrx<=vrmax) & (vrx>=vrmin)]
    vry = vry[(vry<=vrmax) & (vry>=vrmin)]
    vrz = vrz[(vrz<=vrmax) & (vrz>=vrmin)]
    vr = np.concatenate((vrx,vry,vrz))
    #vr = np.sqrt(vrx**2+vry**2+vrz**2)
    vr.sort()
    print(vr.shape)
    
    vr_prime =(vr[:-1] + vr[1:]) / 2
    print(len(vr_prime))
    line_bins = np.zeros((len(vr_prime),3))
    for i in range(len(vr_prime)):
        v_prime = pk + vr_prime[i]*rhat
        line_bins[i] += np.floor((v_prime-vmin)/ dv)
    
    
    line_bins = line_bins.astype(int)
    #line_bins, unique_ind = np.unique(line_bins,axis=0,return_index=True)
    print(line_bins.shape)
    
    #line_len = vr[1:]-vr[:-1]
    line_len = vr[1:]-vr[:-1]
    non_zero = np.nonzero(line_len)
    line_len = line_len[non_zero]
    line_bins = line_bins[non_zero]
    #line_len = line_len[unique_ind]
    
    K[line_bins[:,0],line_bins[:,1],line_bins[:,2]] = line_len/(dvx*dvy*dvz)
    
    return K, line_bins, line_len, vr

In [190]:
nx,ny,nz = 30,30,30
hx,hy,hz = 10,10,10
phi = np.zeros((nx,ny,nz)) # First test

b = np.deg2rad(10.) # just a test
l = np.deg2rad(30.)
cosl = np.cos(l)
cosb = np.cos(b)
sinl = np.sin(l)
sinb = np.sin(b)
s = 0.1

mul,mub=2,1

rhat = np.array([cosb*cosl, cosb*sinl, sinb])

#S = np.array([[-sinl,cosl,0],
#              [-sinb*cosl,-sinb*sinl,cosb]])

p = s*np.array([-sinl*cosb*mul - cosl*sinb*mub,
                 cosl*cosb*mul - sinl*sinb*mub,
                 cosb*mub])

rhat = np.array([1,1,1])
#p = np.array([0,0,0])

In [191]:
#Testing K

K, lb, ll, vr = calc_K(p,rhat,0,hx,nx,0,hy,ny,0,hz,nz)

ValueError: rhat must be a unit vector

In [189]:
print(ll)
print(lb)
print(vr)

[ 11.72513655   8.12151547   3.60362109  11.72513655   4.9797746
   6.74536196   9.98692768   1.73820887   1.83803373   9.88710283
  10.42142941   1.30370714  11.72513655   7.27968854   4.44544802
   8.94894974   2.77618681   4.13794767   7.58718889  11.72513655
   0.9962068   10.72892976   9.57960248   2.14553407   7.9109718
   3.81416475   6.43786161   5.28727494  11.72513655   3.29612074
   8.42901582  11.72513655   0.15437987   6.71861399   4.85214269
   8.73777555   2.987361    11.72513655   5.59603468   6.12910187
  11.72513655   2.45429381   3.38072211   5.89012063  11.03768949
   0.68744706  11.72513655   7.89594862   3.82918793  11.72513655
   4.75420775   0.04283023   6.92809857]
[[ 0  0  0]
 [ 1  0  0]
 [ 1  1  0]
 [ 2  1  0]
 [ 3  1  0]
 [ 3  2  0]
 [ 4  2  0]
 [ 4  2  1]
 [ 5  2  1]
 [ 5  3  1]
 [ 6  3  1]
 [ 6  4  1]
 [ 7  4  1]
 [ 8  4  1]
 [ 8  5  1]
 [ 9  5  1]
 [ 9  5  2]
 [10  5  2]
 [10  6  2]
 [11  6  2]
 [12  6  2]
 [12  7  2]
 [13  7  2]
 [13  8  2]
 [14  8  2]
 